version: '3.8'

services:
  app:
    image: 'sports-platform:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/sports_platform_db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GRPC_PDF_SERVER_HOST=grpc-server
      - GRPC_PDF_SERVER_PORT=50051
      - JAVA_OPTS=-Xmx1024m -Xms512m -Dfile.encoding=UTF-8 -Duser.timezone=UTC
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - shared-network

  db:
    image: 'postgres:14.7-alpine'
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  db-data:

networks:
  shared-network:
    external: true